### ISSUE TITLE
[REDESIGN] Open Unicord from the System Tray doesn't work.

### ISSUE THREAD

**Issue by OnlyEnderMax** [WamWooWam/Unicord#101]
Having enabled the Background Notifications option on Unicord put it in the System Tray. When trying to open Unicord from there with right click and choosing the option to "Open Unicord" it doesn't never open.

**Comment by RoboMWM** [comment]
This also applies to v1.8.1. The app will open but hang on the splash screen. Closing the app in this state will cause it to reopen again (to a frozen splash screen again). You have to close it twice quickly for it to close, or zap its process in task manager.
