### ISSUE TITLE
[REDESIGN] The profile view no longer loads on Alpha 5

### ISSUE THREAD

**Issue by OnlyEnderMax** [WamWooWam/Unicord#116]
The title is self-explanatory. 
![image](https://github.com/user-attachments/assets/27a71dfb-0445-49c5-ae29-9ccbd8961126)

**Comment by WamWooWam** [comment]
Is this fixed in more recent alphas?

**Comment by OnlyEnderMax** [comment]
Yes it was fixed the previously alpha, efficient staff!
