### ISSUE TITLE
[REDESIGN] The overlay and Normal windows for chats don't work on Alpha 5

### ISSUE THREAD

**Issue by OnlyEnderMax** [WamWooWam/Unicord#117]
![image](https://github.com/user-attachments/assets/e47814f5-e305-46d8-9fad-86ebde14388c)

**Comment by WamWooWam** [comment]
Should've fixed this, if you're using the `.appinstaller` it should work in `2.0.16-d5303a9` and later, new alpha coming soon™️

**Comment by OnlyEnderMax** [comment]
It's working now, nice work there!
