### ISSUE TITLE
Is it possible to install Unicord on a Lumia 435 with WP10 1607?

### ISSUE THREAD

**Issue by trainman313** [WamWooWam/Unicord#124]
I've been trying to install beta 1.8.1.0 onto my Lumia 435. After installing the certificate, when I go to install the app itself, it prompts me to install it and when I press yes, the screen goes white for a second and then back to the files screen and no app is installed. Am I doing something wrong or is the WP10 version not supported?

**Comment by WamWooWam** [comment]
Unicord requires Windows 10 build 15035 or later. Sorry!
