### ISSUE TITLE
[REDESIGN] [Feature] Option to only load channel list on clicking guild (restore 1.8.x navigation)

### ISSUE THREAD

**Issue by RoboMWM** [WamWooWam/Unicord#129]
I would like an option to restore the way 1.8.x navigated between guilds - which is loading only the guilds channel list, not also a channel, upon clicking the guild.

- More responsive:
  - when width is constrained (such as on phone), the channel list is immediately visible and saves me from having to both wait for the channel to load, and tap the hamburger button again
  - especially if the channel I wish to load is not the one I was last in
  - I can still view messages from the previous channel while browsing to see what unread channels I have in other guilds

Some additional options that could be added:
- The feature is "toggled" if guild is double clicked/double tapped (i.e., double-tapping/clicking the guild icon would cause it to load the last channel immediately as it currently does in 2.x, whereas single tap/click would only load channel list - and this behavior could be reversed if desired).

**Comment by WamWooWam** [comment]
Added in v2.0.0-beta.2 :)
