### ISSUE TITLE
Cannot create instance of type. [Failed to login!]

### ISSUE THREAD

**Issue by shawny43** [WamWooWam/Unicord#136]
![image](https://github.com/user-attachments/assets/62605ebb-c57b-462d-a02c-bec501cda180)

The text associate to the code error was not found. 

Cannot create instance of type.
'Unicord.Universal.Models.FriendsPageViewModel' ­[Line: 0 Position: 0]

### Steps to reproduce.

- Pick the token from developer console on my browser.
- Log-in
- Receive error.

**Comment by WamWooWam** [comment]
Fixed in v2.0.0-beta.3 :)
