### ISSUE TITLE
Freze and crash after 3 seconds when switching to direct messeges\people

### ISSUE THREAD

**Issue by FandyME** [WamWooWam/Unicord#140]
OS: Windows 10 1809 LTSC. Official unmodified ISO from Microsoft. Fresh install
Device: Surface Pro 7
Versions: From 2.0.0 Alpha 11 to 2.0.0 Beta 3
Crash dump: https://www.mediafire.com/file/6x4v9clqrem8a5i/Unicord.Universal.exe.3600.dmp/file

When opening the people\DM section Unicord freezes and 3 seconds after that crashes\closes. If I quickly switch to a server on startup Unicord remains stable and works fine. If I select people\DMs after that same behavior (freeze and then crash)

**Comment by kuildor** [comment]
Can confirm that bug is still happening on Windows 11 24H2 LTSC. I dont know how to grab crash logs, so, idk how to send it.

**Comment by FandyME** [comment]
Fixed in beta 3a
