### ISSUE TITLE
Theming Improvements

### ISSUE THREAD

**Issue by WamWooWam** [WamWooWam/Unicord#29]
Themes could do with a little bit of work. Here's what I've got planned:
 - [x] Load multiple themes at once
    - [ ] ~~Theme dependencies~~
 - [ ] Theme versioning
 - [x] Better handling of XAML parse errors and invalid themes
    - [x] Better UX for themes that fail to load on launch
    - [x] Validate XAML at install time
- [ ] Ability to enforce light/dark mode in a theme

**Comment by yuezhengbaizhi** [comment]
also can you add an opition to disable flued design? it makes my lumia become laggy

**Comment by WamWooWam** [comment]
> also can you add an opition[sic] to disable flued[sic] design? it makes my lumia become laggy 

This can be achieved through a custom theme, which will probably be inbox in future.

**Comment by WamWooWam** [comment]
I've decided it's not worthwhile to do dependencies for themes. To do this properly I'd end up with almost a complete dependency management system complete with updates and downloads and such.

In other words, a package manager. No thanks.
