### ISSUE TITLE
Using reply and quotes 

### ISSUE THREAD

**Issue by sprainbrains** [WamWooWam/Unicord#39]
Hello!

I don't know how to use reply and quotes inside Unicord. I didn't find instruction how to do it.

Unicord version: 1.6.6.0

**Comment by WamWooWam** [comment]
Plain and simple, these features don't exist yet, and I don't wanna pull a Discord and do a half-assed implementation based on markdown blockquotes.

Eventually there'll be proper quotes built using embeds (or if Discord ever get around to real quotes at an API level, that). There is no ETA on this.

**Comment by sprainbrains** [comment]
> Plain and simple, these features don't exist yet, and I don't wanna pull a Discord and do a half-assed implementation based on markdown blockquotes.
> 
> Eventually there'll be proper quotes built using embeds (or if Discord ever get around to real quotes at an API level, that). There is no ETA on this.

Ok. But what about search user by nickname? I mean when i write @ symbol into chat textfield so UniCord will show me all list nickname users in the current chat. I can help to write correct answer for users.

**Comment by WamWooWam** [comment]
This also doesn't exist yet.

**Comment by sprainbrains** [comment]
> This also doesn't exist yet.

Got it. It's sadly(

**Comment by WamWooWam** [comment]
> Ok. But what about search user by nickname? I mean when i write @ symbol into chat textfield so UniCord will show me all list nickname users in the current chat

This is now in testing!
https://github.com/WamWooWam/Unicord/releases/tag/v1.6.16-beta
