### ISSUE TITLE
Certificate included in latest release is expired

### ISSUE THREAD

**Issue by LennyPenny** [WamWooWam/Unicord#44]
Hey, awesome project! 
I was trying to install the latest release from https://github.com/WamWooWam/Unicord/releases

When I tried to install the appxbundle it said I need a certificate. I tried installing the cert provided in the release, but that seems to be expired. 
Would it be possible for you to provide a release with an updated certificate? 

![image](https://user-images.githubusercontent.com/4027243/87606684-e1773b80-c6fb-11ea-8be4-8ad803492774.png)

**Comment by WamWooWam** [comment]
Hi yes, I'm working on it, in the meantime you can set your clock back. I'll have a release out soon:tm:

**Comment by WamWooWam** [comment]
I think this should do it :P
https://github.com/WamWooWam/Unicord/releases/tag/v1.6.16-beta
