### ISSUE TITLE
Linux support? [enchantment]

### ISSUE THREAD

**Issue by sijanec** [WamWooWam/Unicord#55]
Hi!

I have no knowledge of the Windows environment and I, as well as many others, would really appreciate if the code would be more cross-platform or at least be able to run and compile on an *X based OS, extending it's use over to the MacOSX and Linux world.

Thanks (;

**Comment by WamWooWam** [comment]
Unfortunately Unicord is based on the Universal Windows Runtime and is inherently tied to the Windows OS. The only way to create a cross platform version would be via the [Uno Project](https://platform.uno/) which is currently in it's infancy

**Comment by WamWooWam** [comment]
idk why this is still open, we've no plans for an uno port right now

**Comment by SimonSeider** [comment]
> Unfortunately Unicord is based on the Universal Windows Runtime and is inherently tied to the Windows OS. The only way to create a cross platform version would be via the [Uno Project](https://platform.uno/) which is currently in it's infancy

I thought you'd use WPF since then someone could port it to Avalonia since WPF and Avalonia have the some structure or simular
