### ISSUE TITLE
Bug: notifications show up from muted dms and the dm becomes unmuted

### ISSUE THREAD

**Issue by KibSquib48** [WamWooWam/Unicord#60]
I have a group dm muted because I'm barely active in it but I don't really feel like leaving, but I keep getting notifications and when I go to check the dm I see that it became unmuted

edit: this happens to channels and servers too

**Comment by WamWooWam** [comment]
This might have been addressed by 1.7.0, please let me know if you're still seeing this behaviour

**Comment by KibSquib48** [comment]
yep, it was fixed in 1.7.0
