### ISSUE TITLE
567 errors what the actual fuck

### ISSUE THREAD

**Issue by Nannnerz** [WamWooWam/Unicord#63]
downloaded the source and then opened it now i have 567 errors and half of the FUCKING FILES THAT ARE SUPPOSED TO BE THERE ARE GONE

**Comment by WamWooWam** [comment]
This is just about the least helpful issue I've ever seen filed against any project, let alone one of my own.

I'm closing this. If you genuinely want help, calm the fuck down and tell me **what's actually wrong**. I'm not a mind reader, I don't know what those errors actually are unless you bother tell me. On top of this people are much more likely to want to help if you don't spam their GitHub issues with vulgar garbage. Thanks :)
