### ISSUE TITLE
Can't install latest release

### ISSUE THREAD

**Issue by ChildishGiant** [WamWooWam/Unicord#65]
There are no install instructions (other than build instructions) so I downloaded the latest release and ran the appxbundle. I get this screen but the install button is greyed out and can't be clicked.

![image](https://user-images.githubusercontent.com/13716824/107434811-285ad180-6b23-11eb-9cff-073d896f8e6a.png)

**Comment by KibSquib48** [comment]
use the install.ps1 file

**Comment by ChildishGiant** [comment]
I tried but it never worked (and seemed a tad dodgy since there's already a certificate)

**Comment by KibSquib48** [comment]
that's what it does though, the install.ps1 installs the cert in the right place and then installs the appx

**Comment by WamWooWam** [comment]
Looks like this was sorted, use the supplied PowerShell script to install the app.
