### ISSUE TITLE
Live tiles and notifications not working on mobile 

### ISSUE THREAD

**Issue by surya-sk** [WamWooWam/Unicord#75]
Not sure if you're still testing on mobile, and I understand if you aren't, but I'm not getting notifications or live tiles on my phone. Both work fine on PC, but not on my Lumia 950. I'm allowing it to run in background and I have notifications turned on. I do get the badge on the app's tile though.

**Comment by LokiMidgard** [comment]
Yesterday I still got notifications on my Lumia 950

**Comment by LokiMidgard** [comment]
I noticed that I somtimes don't get notifications. One instance I got notifications on my PC and a minute later I unlocked my phone the notification arrived when I turnd on the screen to unlock. I would asume not arriving notifications are due to Windows Phone optimizing for batery life time.

**Comment by surya-sk** [comment]
You're probably right. I'm having to reset my phone for another reason, so I'll see if anything changes after.

**Comment by WamWooWam** [comment]
Notifications don't work on mobile. They depend on a background process. You can't launch background processes on mobile lol
