### ISSUE TITLE
Um, what is happening now?

### ISSUE THREAD

**Issue by Jimmy-Blue** [WamWooWam/Unicord#77]
I recently downloaded and use Unicord, as the official Discord client heavy and slow and so far was good until this happened. Is this a false alarm or not? As I don't want to be attacked the 5th time of this year anymore. Too enough for reinstalling Windows.

![image](https://user-images.githubusercontent.com/60958064/131307068-3dcb2ff1-650e-4c78-bee0-48ef1c8f3bda.png)

**Comment by heftymouse** [comment]
It's a false alarm, don't worry
Someone sent you an image that contains some VBScript or something at the end of the file, which makes AVs think it's malicious, but it's really not

**Comment by Jimmy-Blue** [comment]
> It's a false alarm, don't worry
> 
> Someone sent you an image that contains some VBScript or something at the end of the file, which makes AVs think it's malicious, but it's really not

I also checked the folder and I just deleted all the files in the Cache and have a full scan of my PC just in case. Luckily, it didn't find anythingg.
