### ISSUE TITLE
[REDESIGN] system messages are blank

### ISSUE THREAD

**Issue by RoboMWM** [WamWooWam/Unicord#96]
System messages (e.g. when a call was started, server join message, etc.) is blank in v2.0.0-alpha.1 and v2.0.0-alpha.2. Issue is not present in v1.8.0 or v1.8.1.

![image](https://github.com/user-attachments/assets/eba0da16-988f-46ce-ae87-3959c7235380)
![image](https://github.com/user-attachments/assets/adfb203a-5594-4d2c-9ac1-6cbad7953d19)

**Comment by RoboMWM** [comment]
Discovered it's all 'system' messages, not just 'started a call' message.

**Comment by RoboMWM** [comment]
My pure uninformed guess is it may be something that got borked when implementing translation

**Comment by WamWooWam** [comment]
even stupider, viewmodel migration thing
